1111
10 1
1111

AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAAA	AAAAAAAA	BBBBBBBB	AAAAAAAA
AAAAAAA	AAAAAAAB	CCCCCCCC	BAAAAAAA

AAAAAAA	21000012	XXXXXXXX	CBAAAAAA
AAAAAAA	21000012	XXXXXXXX	CBAAAAAA
AAAAAAA	21000012	XXXXXXXX	CBAAAAAA
AAAAAAA	21000012	XXXXXXXX	CBAAAAAA
AAAAAAA	21000012	XXXXXXXX	CBAAAAAA
AAAAAAA	21000012	XXXXXXXX	CBAAAAAA
AAAAAAA	21000012	XXXXXXXX	CBAAAAAA
AAAAAAA	21000012	XXXXXXXX	CBAAAAAA

AAAAAAA	AAAAAAAB	CCCCCCCC	BAAAAAAA
AAAAAAA	AAAAAAAA	BBBBBBBB	AAAAAAAA
AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
