1111
10 1
1111

AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAA1	AAAAAAAA	BBBBBBBB	AAAAAAAA
AAAAAA2	1AAAAAAA	CCCCCCCC	AAAAAAAA

AAAAAAx	21000012	XXXXXXXX	AAAAAAAA
AAAAAAx	21000012	XXXXXXXX	AAAAAAAA
AAAAAAx	21000012	XXXXXXXX	AAAAAAAA
AAAAAAx	21000012	XXXXXXXX	AAAAAAAA
AAAAAAx	21000012	XXXXXXXX	AAAAAAAA
AAAAAAx	21000012	XXXXXXXX	AAAAAAAA
AAAAAAx	21000012	XXXXXXXX	AAAAAAAA
AAAAAAx	21000012	XXXXXXXX	AAAAAAAA

AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
AAAAAAA	AAAAAAAA	AAAAAAAA	AAAAAAAA
